# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: lorasensornetwork.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='lorasensornetwork.proto',
  package='lorasensornetwork',
  syntax='proto3',
  serialized_options=None,
  serialized_pb=_b('\n\x17lorasensornetwork.proto\x12\x11lorasensornetwork\"\xcb\x01\n\x06Packet\x12\x0e\n\x06src_id\x18\x01 \x01(\x0c\x12\x0f\n\x07\x64\x65st_id\x18\x02 \x01(\x0c\x12\x37\n\x08msg_type\x18\x03 \x01(\x0e\x32%.lorasensornetwork.Packet.MessageType\x12\x0f\n\x07payload\x18\x04 \x01(\x0c\"V\n\x0bMessageType\x12\x10\n\x0cJOIN_REQUEST\x10\x00\x12\x0c\n\x08JOIN_ACK\x10\x01\x12\x13\n\x0fSENSOR_RESPONSE\x10\x02\x12\x12\n\x0eSENSOR_REQUEST\x10\x03\x62\x06proto3')
)



_PACKET_MESSAGETYPE = _descriptor.EnumDescriptor(
  name='MessageType',
  full_name='lorasensornetwork.Packet.MessageType',
  filename=None,
  file=DESCRIPTOR,
  values=[
    _descriptor.EnumValueDescriptor(
      name='JOIN_REQUEST', index=0, number=0,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='JOIN_ACK', index=1, number=1,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='SENSOR_RESPONSE', index=2, number=2,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='SENSOR_REQUEST', index=3, number=3,
      serialized_options=None,
      type=None),
  ],
  containing_type=None,
  serialized_options=None,
  serialized_start=164,
  serialized_end=250,
)
_sym_db.RegisterEnumDescriptor(_PACKET_MESSAGETYPE)


_PACKET = _descriptor.Descriptor(
  name='Packet',
  full_name='lorasensornetwork.Packet',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='src_id', full_name='lorasensornetwork.Packet.src_id', index=0,
      number=1, type=12, cpp_type=9, label=1,
      has_default_value=False, default_value=_b(""),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='dest_id', full_name='lorasensornetwork.Packet.dest_id', index=1,
      number=2, type=12, cpp_type=9, label=1,
      has_default_value=False, default_value=_b(""),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='msg_type', full_name='lorasensornetwork.Packet.msg_type', index=2,
      number=3, type=14, cpp_type=8, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='payload', full_name='lorasensornetwork.Packet.payload', index=3,
      number=4, type=12, cpp_type=9, label=1,
      has_default_value=False, default_value=_b(""),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
    _PACKET_MESSAGETYPE,
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=47,
  serialized_end=250,
)

_PACKET.fields_by_name['msg_type'].enum_type = _PACKET_MESSAGETYPE
_PACKET_MESSAGETYPE.containing_type = _PACKET
DESCRIPTOR.message_types_by_name['Packet'] = _PACKET
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

Packet = _reflection.GeneratedProtocolMessageType('Packet', (_message.Message,), {
  'DESCRIPTOR' : _PACKET,
  '__module__' : 'lorasensornetwork_pb2'
  # @@protoc_insertion_point(class_scope:lorasensornetwork.Packet)
  })
_sym_db.RegisterMessage(Packet)


# @@protoc_insertion_point(module_scope)
